version: '3.9'

services:
  app:
    build: .
    container_name: felchat_app
    working_dir: /app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql+psycopg2://felchat:felchat@db:5432/felchat
      - REDIS_URL=redis://redis:6379/0
      - ENV=prod
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    container_name: felchat_db
    restart: always
    environment:
      POSTGRES_USER: felchat
      POSTGRES_PASSWORD: felchat
      POSTGRES_DB: felchat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: felchat_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: 